# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk11
services:
  - postgresql
before_install:
  - psql -c 'create database tracker;' -U postgres
script:
  - mvn install
# используем режим обычного пользователя для сборки проекта.
sudo: true

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - gartel47@gmail.com
    on_success: never # default: change
    on_failure: always # default: never

env:
  global:
    - CODECOV_TOKEN="a7bceef9-6182-40c2-a188-eaee92a139f9"